### ISSUE TITLE
Kotlin RIB templates

### ISSUE THREAD

**Issue by oronbz** [uber/RIBs#144]
Hi,
Are Kotlin templates in the making? Is this something you thought of, or decided to discard?

**Comment by AttwellBrian** [comment]
No reason not to have kotlin templates.

I haven't built kotlin templates because we don't use kotlin in production apps. Kotlin slows build performance in highly modular apps (going from a 12second incremental build time to minutes in one of our apps). But I'd be happy to take a PR that adds kotlin templates.

**Comment by oronbz** [comment]
Sounds good, I'll try to work something out (:

**Comment by rendecano** [comment]
Sample project using Kotlin, but no templates yet. :(

https://github.com/rendecano/CoinEdge

**Comment by hzsweers** [comment]
To elaborate a bit on @AttwellBrian's comment - the problem for us is buck's lack of tooling for kotlin. We don't have any metrics on kotlin's incremental compilation in a gradle project though

**Comment by rendecano** [comment]
Created an initial version of Kotlin templates.

https://github.com/rendecano/RIBsKotlinPlugin

I'm not sure if I should create a PR for this though. :)

**Comment by AttwellBrian** [comment]
Sorry about slow reply. Holidays and what-not. Will reply on the pull request.
