### ISSUE TITLE
Best practices for routers about closing current ViewController.

### ISSUE THREAD

**Issue by igordeoliveirasa** [uber/RIBs#157]
I'd like to learn what's the best practice for routers in order to close (dismiss or pop) current opened UIViewController. I don't think it's nice to make multiples conditions in "currentChild" to discover which view it is and suppose that: Oh ok, its AViewController, lets dismiss it, but if it's BViewController let's pop it... Because,.. I could have moments where AViewController could be a modal and another situations where it could not be modal but pushed.

I also think that "detachCurrentChild" method explained on tutorial is a bit coupled, since it detaches current child and also dismiss current view. Let's decouple this method and learn a good way to dismiss/pop current view controller?

So, since we don't have a more complex example, I opened this question.

**Comment by neakor** [comment]
How to present and dismiss child view controllers (push vs modal) is inherently a view logic concern. The router shouldn't be making this decision anyways. It should delegate that to the corresponding view/view controller. For instance, after the router detaches the child RIB, it can simply make a call via its `MyViewControllable` protocol to tell the corresponding view controller implementation to "remove" the child view controller. The parent view controller can decide what style to use for the removal based on view states.

**Comment by igordeoliveirasa** [comment]
@neakor do you have any practical example using modal and navigation?

**Comment by neakor** [comment]
We do have a lot of examples internally at Uber. Unfortunately those examples are too complex to share in a digestible format. In short though, once we get to the corresponding view controller implementation from the router, there's not much difference between how a RIB's view controller operates from how a MVC's view controller operates.

**Comment by igordeoliveirasa** [comment]
@neakor 
> The parent view controller can decide what style to use for the removal based on view states.

I didn't understand exactly this part.

**Comment by neakor** [comment]
I think you got it right. The implementation of those methods should encapsulate all view logic related to dismissing the view controller passed in.

**Comment by JakeSc** [comment]
> Oh ok, its AViewController, lets dismiss it, but if it's BViewController let's pop it 

We've done something similar, @igordeoliveirasa, whereby our ViewController has some method like this:
```
func detach(childView: ViewControllable) {
    if childView is ChildType1 {
        childView.dismissWithAnimation()
    } else {
        childView.dismissWithoutAnimation()
    }
    // etc.
}
```

Although this is a bit messy given the `switch` statement, I think it's defensible for the parent ViewController to make certain view-logic decisions based on its child's type. It can have full knowledge of all its children types. Another, slightly more generic way we have solved this is by moving _some_ of the dismissing logic into the Router:
```
view.dismissPrimaryChild()
view.dismissAuxiliaryChild()
```
, whereby the ViewController sort of defines that it supports displaying/dismissing two separate types of child views.

However, I still prefer the first option because, as @neakor says, the Router should have no knowledge about _how_ the Views are shown/hidden.

**Comment by igordeoliveirasa** [comment]
Awesome, @JakeSc and @neakor.

I really got it. Thank you so much guys.
