### ISSUE TITLE
Question: when is cleanupViews called?

### ISSUE THREAD

**Issue by igordeoliveirasa** [uber/RIBs#173]
I've read tutorial many times however I didn't get when cleanupViews is called.

**Comment by sbarow** [comment]
Its defined by the user. There is an explanation as to why you use it in [tutorial 2](https://github.com/uber/RIBs/wiki/iOS-Tutorial-2#cleaning-up-attached-views-when-the-loggedin-rib-is-detached) 

Regarding when it is called if you have a look at the [LoggedInInteractor.swift](https://github.com/uber/RIBs/blob/master/ios/tutorials/tutorial4-completed/TicTacToe/LoggedIn/LoggedInInteractor.swift) in `ios/tutorials/tutorial4-completed` we can see its called in `override func willResignActive()` which happens when you `detachChild`

From `Interactor.swift`

```
/// Callend when the `Interactor` will resign the active state.
///
/// This method is driven by the detachment of this interactor's owner router. Subclasses should override this
/// method to cleanup any resources and states of the `Interactor`. The default implementation does nothing.
open func willResignActive() {
    // No-op
}
```

**Comment by igordeoliveirasa** [comment]
@sbarow thank you. technically I got it however, when it's "real life" it's not so easy to get it..
By the way, could you help me at: #174 ? I can't see where I'm making mistake...
