### ISSUE TITLE
Example of Worker

### ISSUE THREAD

**Issue by kronik** [uber/RIBs#206]
Any good explanation or example of Worker?

**Comment by AttwellBrian** [comment]
Good point. Don't think we wrote any tutorials around this. There are a very simple class. Some thoughts.

**Question**: What we use workers for?
Answer: suppose you have a RIB that contains a bunch of stateful code or Rx subscriptions for the sake of different features - none of which modifies the UI. For example: one feature might prefetche some state from a server that may be useful for later. Another feature might talk to a third party analytics vendor. If this code can be partitioned into isolated classes it enhances readability. You no longer have to wonder which parts of the RIB are coupled with each other parts of the RIB.  So we put this code into Workers.

**Question**: Why even use workers instead of just creating a new appropriate blank class from scratch for every isolated feature? 
**Answer**: Two reasons (1) nice to define consistent patterns and naming. You want to extract independent lifecycled code into its own class --> create a worker (2) having the standard base interface makes it a bit easier to abstract away the features. The RIB can just start a list of Workers it recieved from DI or an abstract factory without knowing their individual names.

**Comment by kronik** [comment]
@AttwellBrian Thanks!

**Comment by ermik** [comment]
Please also see #269 #232 as well as #170.
