### ISSUE TITLE
Why `Routing` instead of `Routable`?

### ISSUE THREAD

**Issue by machty** [uber/RIBs#217]
Hi there, currently learning RIBs, and while I understand the heavy use of protocols to facilitate stubbing/mocking in a test environment, one thing that tripped me up (possibly more than it should have) is the fact that most of the protocols in RIB use `-able` as a suffix (e.g. Presentable, Interactable, Buildable) but some reason the protocol that Routers implement is called `Routing`, which, as I'm parsing the tutorials/docs and trying to parcel out what's a concrete class and what's a protocol, would frequently trip me up. Is there some reason it isn't called Routable? Is it too late for a rename?

**Comment by kronik** [comment]
I had the same question in my mind...

**Comment by igordeoliveirasa** [comment]
I also got this question in my mind...

**Comment by artman** [comment]
I'm not really sure myself. I remember that we had discussions around this, and we discussed whether we should adapt the common iOS norm of using a gerund ("...ing") form for protocol names. I think we just thought `Interacting` sounded dumb and so we used `Interactable` and `Presentable`. `Routing` stayed `Routing` since `Routable` sounded too much like **it** could be routed, not that it would manage the routing.
