### ISSUE TITLE
[Android] Could I use Context to open an activity in Router?

### ISSUE THREAD

**Issue by Hayashi2026** [uber/RIBs#221]
I am refactoring my app with RIBs. I refactor my project step by step, so only one activity of my project would use RIBs, other activities use a kind of MVVM. So, I get a problem. I need to open other activities in Router class, It's not the same as what tutorials teach. I need to get an activitiy's context in the Router class.  I can get context from the view, but Is it a right way to do that?

**Comment by sbarow** [comment]
Whats the definition of "context" in this situation? Generally the direction of communication from a view would be:

- View -> Listener (Interactor)
- Interactor -> Listener or Router (interactor determines business logic)
- Router determine were to route to next.

**Comment by Hayashi2026** [comment]
@sbarow “context” means Activity’ context， Context.class in Android，I need to call context.startActivity() in Router.

**Comment by AttwellBrian** [comment]
You could definitely pull the context down the DI graph and provide it to the router. I would do one of two approaches:
* Instantiate the router with a context so that the interactor can call `router.showNewActivity()`. This way you can mock out the router and easily test this flow. Plus it looks similarly to how you show new RIBs. So will be less confusing to future readers of your code.
* Wrap the context in an ActivityShower interface. This can be mocked and tested just as easily as the router. And this could be used to avoid passing around the whole context through the DI graph if you don't like the idea of passing around a god object.

**Comment by Hayashi2026** [comment]
@AttwellBrian thanks, I think this solves the problem
