### ISSUE TITLE
Android tutorials without Dagger

### ISSUE THREAD

**Issue by bantyK** [uber/RIBs#228]
The tutorials are very difficult to follow if you have no or very limited knowledge of Dagger. Is there any sample project available in Android (Java/Kotlin) where this architecture is implemented without using Dagger.

**Comment by AttwellBrian** [comment]
> The tutorials are very difficult to follow if you have no or very limited knowledge of Dagger.

Dagger does throw a lot of concepts at you at once!

> Is there any sample project available in Android (Java/Kotlin) where this architecture is implemented without using Dagger.

None that I know of. It wouldn't be too hard to write some samples. But it might be faster to gain a basic working knowledge of dagger :)

I'm hesitant to include samples without dagger, since almost all real world consumers will use dagger.

The main reason RIBs are independent from Dagger is so that you can choose to use an alternative DI (or build your own micro DI framework). The objective wasn't to allow engineers to avoid DI frameworks altogether.

**Comment by bantyK** [comment]
That makes a lot of sense. Thank you.
