### ISSUE TITLE
Networking best practice 

### ISSUE THREAD

**Issue by davidseek** [uber/RIBs#278]
Hey guys,

I'm curious of what you'd suggest as best practice to implement a networking layer.
As an example, let's take a social media App with a User model.
This model can be edited at several locations in the App.
For example the User can like something, he can add something, bookmark something.
For the sake of the argument let's say that all likes, bookmarks, adds are stored into user model itself.
Like `user.likes`.

How would you handle the database upload?
I see 3 options.
Singleton what I'm trying to avoid. 
Where I then would have something like `DatabaseUploader.shared.upload<T>`.

The second option would be a DatabaseUploader that has to be injected 
through dependency injection wherever needed. 
So we would pass the model down from init to all the children.

Third option I see and commonly use is a `DatabaseManager` class somewhere around the App entry and then a protocol `DatabaseUploader` where I then have all the desired use cases conform too.

But what's the best practice approach following the RIB architecture? 
Thank you for your time.

**Comment by ermik** [comment]
I think interfacing through Rx is best bet for decoupled architecture such as RIBs. Any given `Interactor`, while holding key business logic, is not supposed to have knowledge about the intricacies of communicating the results of that logic to any other entity within the app, let alone communicating with storage or over the wire/air. So second option you've described is the closest, but you should pass an Rx primitive, not the actual `DatabaseUploader`, while it would subscribe to the data IO tasks _agnostically_ dispatched elsewhere.

Also, the app shouldn't know that there is a Database. It should talk to an API. The API may want to print out the results and publish a book instead of using fancy-shmancy databases. 😆

**Comment by davidseek** [comment]
Understood. That makes a lot of sense.
Thank you for the insight and I will implement it like that.
Right now I have implemented it like in the 2nd option.
But I will replace it with an Rx primitive. Thank you!
